name: vxkonsol
description: "A new Visual & Extendable Console Project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  hotkey_manager: ^0.2.3
  get: ^4.7.2
  fluentui_system_icons: ^1.1.259
  window_manager: ^0.4.3
  flutter_acrylic: ^1.1.4
  gradient_borders: ^1.0.1
  flutter_bloc: ^9.1.0
  path: ^1.8.3
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_staggered_animations: ^1.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true


  assets:
    - assets/icons/VXKonsolPNG.png
    - assets/icons/VXKonsolPNG2.png


  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata/Inconsolata-VariableFont_wdth,wght.ttf

    - family: IBM Plex Mono
      fonts:
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexMono/IBMPlexMono-Bold.ttf
          weight: 700
  #

flutter_launcher_icons: #run dart run flutter_launcher_icons
  # android: "launcher_icon"
  # ios: true
  # image_path: "assets/icon/icon.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/VXKonsolPNG5.png"
    icon_size: 64
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"